// <auto-generated />
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebHosting.DataAccessLayer.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebHosting.EntityLayer.Entities.Hosting", b =>
                {
                    b.Property<string>("HostingDomainName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CpuLoad")
                        .HasColumnType("int");

                    b.Property<string>("HostingPackage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IncomingConnections")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RamMax")
                        .HasColumnType("int");

                    b.Property<int>("RamUsage")
                        .HasColumnType("int");

                    b.HasKey("HostingDomainName");

                    b.ToTable("Hostings");
                });
#pragma warning restore 612, 618
        }
    }
}
